version: "2.1"
services:
  mariadb:
    image: linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ALLOW_EMPTY_PASSWORD="true"
    volumes:
      - .db:/config
    ports:
      - 8080:8080

  ba_sql:
    container_name: ba_sql
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    environment:
      PORT: "8080"
    volumes:
      - ./results:/results
